// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using RoboticsOutreach.Inventory.Infrastructure;

#nullable disable

namespace RoboticsOutreach.Inventory.Infrastructure.Migrations
{
    [DbContext(typeof(InventoryContext))]
    [Migration("20250425121705_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.BomItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("IngredientTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<int>("Quantity")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IngredientTypeId");

                    b.HasIndex("ItemTypeId");

                    b.ToTable("BomItems");
                });

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.InventoryItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime?>("AcquiredAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("AcquiredPrice")
                        .HasColumnType("integer");

                    b.Property<string>("AssetTag")
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ItemTypeId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("SerialNumber")
                        .HasColumnType("text");

                    b.Property<int>("State")
                        .HasColumnType("integer");

                    b.Property<string>("Summary")
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ItemTypeId");

                    b.HasIndex("LocationId");

                    b.ToTable("InventoryItems");
                });

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.InventoryItemType", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasColumnType("text");

                    b.Property<bool>("IsConsumable")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("ManufacturerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ModelName")
                        .HasColumnType("text");

                    b.Property<string>("ResupplyUri")
                        .HasColumnType("text");

                    b.Property<int?>("UnitPrice")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UnitPriceDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("ManufacturerId");

                    b.ToTable("InventoryItemTypes");
                });

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.Organisation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.BomItem", b =>
                {
                    b.HasOne("RoboticsOutreach.Inventory.Domain.Models.InventoryItemType", "IngredientType")
                        .WithMany()
                        .HasForeignKey("IngredientTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoboticsOutreach.Inventory.Domain.Models.InventoryItemType", "ItemType")
                        .WithMany("BomItems")
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IngredientType");

                    b.Navigation("ItemType");
                });

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.InventoryItem", b =>
                {
                    b.HasOne("RoboticsOutreach.Inventory.Domain.Models.InventoryItemType", "ItemType")
                        .WithMany()
                        .HasForeignKey("ItemTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RoboticsOutreach.Inventory.Domain.Models.InventoryItem", "Location")
                        .WithMany()
                        .HasForeignKey("LocationId");

                    b.Navigation("ItemType");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.InventoryItemType", b =>
                {
                    b.HasOne("RoboticsOutreach.Inventory.Domain.Models.Organisation", "Manufacturer")
                        .WithMany()
                        .HasForeignKey("ManufacturerId");

                    b.Navigation("Manufacturer");
                });

            modelBuilder.Entity("RoboticsOutreach.Inventory.Domain.Models.InventoryItemType", b =>
                {
                    b.Navigation("BomItems");
                });
#pragma warning restore 612, 618
        }
    }
}
